/**
 * Constantes de Estados del Sistema
 * Define todos los estados posibles de una factura
 */

const ESTADOS = {
    RUTA_1: 'RUTA_1',
    RUTA_2: 'RUTA_2', // Legacy - mantener para compatibilidad
    RUTA_2_CONTROL_INTERNO: 'RUTA_2_CONTROL_INTERNO',
    RUTA_2_DIRECCION_MEDICA: 'RUTA_2_DIRECCION_MEDICA',
    RUTA_2_DIRECCION_FINANCIERA: 'RUTA_2_DIRECCION_FINANCIERA',
    RUTA_2_DIRECCION_ADMINISTRATIVA: 'RUTA_2_DIRECCION_ADMINISTRATIVA',
    RUTA_2_DIRECCION_GENERAL: 'RUTA_2_DIRECCION_GENERAL',
    RUTA_3: 'RUTA_3',
    RUTA_4: 'RUTA_4',
    FINALIZADA: 'FINALIZADA',
    ANULADA: 'ANULADA'
};

// Estados de Ruta 2 agrupados para facilitar validaciones
const ESTADOS_RUTA_2 = [
    ESTADOS.RUTA_2,
    ESTADOS.RUTA_2_CONTROL_INTERNO,
    ESTADOS.RUTA_2_DIRECCION_MEDICA,
    ESTADOS.RUTA_2_DIRECCION_FINANCIERA,
    ESTADOS.RUTA_2_DIRECCION_ADMINISTRATIVA,
    ESTADOS.RUTA_2_DIRECCION_GENERAL
];

module.exports = {
    ESTADOS,
    ESTADOS_RUTA_2
};
