/**
 * Constantes de Roles del Sistema
 * Define todos los roles de usuario disponibles
 */

const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    RUTA_1: 'RUTA_1',
    RUTA_2: 'RUTA_2', // Legacy
    RUTA_2_CONTROL_INTERNO: 'RUTA_2_CONTROL_INTERNO',
    RUTA_2_DIRECCION_MEDICA: 'RUTA_2_DIRECCION_MEDICA',
    RUTA_2_DIRECCION_FINANCIERA: 'RUTA_2_DIRECCION_FINANCIERA',
    RUTA_2_DIRECCION_ADMINISTRATIVA: 'RUTA_2_DIRECCION_ADMINISTRATIVA',
    RUTA_2_DIRECCION_GENERAL: 'RUTA_2_DIRECCION_GENERAL',
    RUTA_3: 'RUTA_3',
    RUTA_4: 'RUTA_4'
};

// Roles de Ruta 2 agrupados
const ROLES_RUTA_2 = [
    ROLES.RUTA_2,
    ROLES.RUTA_2_CONTROL_INTERNO,
    ROLES.RUTA_2_DIRECCION_MEDICA,
    ROLES.RUTA_2_DIRECCION_FINANCIERA,
    ROLES.RUTA_2_DIRECCION_ADMINISTRATIVA,
    ROLES.RUTA_2_DIRECCION_GENERAL
];

module.exports = {
    ROLES,
    ROLES_RUTA_2
};
